min_version = "2026.7.5"

[settings]
lockfile = true

[tools]
biome = "2.4.13"
bun = "1.3.14"
node = "24.18.0"
"aqua:jdx/aube" = "1.28.0"

[task_config]
includes = [
  "git::https://github.com/iwamot/mise-tasks.git//.mise/tasks?ref=v2.5.0",
]
