name: Compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  compatibility:
    permissions:
      contents: read
    uses: iwamot/workflows/.github/workflows/compatibility-node.yml@873e99243e0ab9f834bb4eb42198f701bfe5c21c # v8.4.0
    with:
      node-versions: '["20","22","24"]'
